oop_django2/week_2/catalog/urls.py
from django.urls import path
from . import views
from django.urls import re_path as url
from .models import Application

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^application/$', views.ApplicationList.as_view(), name='application'),
    url(r'^application/create/$', views.ApplicationCreate.as_view(), name='application-create'),
    url(r'^application/(?P<pk>\d+)/delete/$', views.ApplicationDelete.as_view(), name='application-delete'),
    path(r'^application/(?P<pk>\w+)/(?P<st>\w+)/update/$', views.confirm_update, name='confirm-update'),
    url(r'^application/application_admin/$', views.ApplicationListAdmin.as_view(), name='application-admin'),
    path('view_categories', views.ViewCategory.as_view(), name='view-categories'),
    path('view_categories/create_category', views.CreateCategory.as_view(), name='create-category'),
    url(r'^category/(?P<pk>\d+)/delete/$', views.DeleteCategory.as_view(), name='delete-category'),
]

oop_django2/week_2/week_2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oop_django2/week_2/catalog/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
import datetime
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
import uuid


def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Максимальный размер файла %sMB" % str(megabyte_limit))


class CustomAccountManager(BaseUserManager):
    def create_user(self, username, fullname, email, password):
        user = self.model(email=email, username=username, fullname=fullname, password=password)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, username, fullname, email, password):
        if not email:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        if not fullname:
            raise ValueError("User must have a full name")
        user = self.model(email=email, username=username, fullname=fullname, password=password)
        user.set_password(password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, username_):
        return self.get(username=username_)


class AdvUser(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True, unique=True)
    username = models.CharField(max_length=200, unique=True, verbose_name='Логин')
    fullname = models.CharField(max_length=200)
    email = models.EmailField(unique=True, max_length=200)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['fullname', 'password', 'email',]

    objects = CustomAccountManager()

    def get_short_name(self):
        return self.username

    def natural_key(self):
        return self.username

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Введите категорию заявки', verbose_name='Название')

    def __str__(self):
        return self.name


class Application(models.Model):
    name = models.CharField(max_length=200, help_text='Введите название заявки', verbose_name='Название')
    summary = models.CharField(max_length=1000, help_text='Введите описание заявки', verbose_name='Описание')
    category = models.ForeignKey('Category', help_text='Выберите категория для заявки', on_delete=models.SET_NULL, null=True, verbose_name='Категория')
    timestamp = models.DateTimeField(default=timezone.now())
    image = models.ImageField(upload_to='images/', validators=[validate_image], help_text='Максимальный размер '
                                                                                          'изображения 2MB', verbose_name='Дизайн(фото)')

    application_status = (
        ('Новая', 'Новая',),
        ('Принято в работу', 'Принято в работу',),
        ('Выполнено', 'Выполнено',)
    )

    status = models.CharField(max_length=50, choices=application_status, blank=True, default='Новая', verbose_name='Статус')
    client = models.ForeignKey(AdvUser, on_delete=models.SET_NULL, null=True, blank=True, to_field='id')
    comment = models.TextField(max_length=500, blank=True)
    design = models.ImageField(upload_to='images/',
                               help_text="Максимальный размер изображения 2MB",
                               blank=True,
                               null=True,
                               validators=[validate_image])

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('profile')

oop_django2/week_2/catalog/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth import password_validation

from catalog.models import AdvUser, Application, Category
from django.core.exceptions import ValidationError


class UserRegistrationForm(forms.ModelForm):
    LetterValidator = RegexValidator(r'^[- а-яА-Я]*$')
    LoginValidator = RegexValidator(r'^[- a-zA-Z]*$')
    username = forms.CharField(validators=[LoginValidator], required=True, label='Логин',
                               help_text='Только латиница и дефис, уникальный')
    fullname = forms.CharField(validators=[LetterValidator], required=True, label='ФИО',
                               help_text='Только кириллические буквы, дефис и пробелы')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    consent = forms.BooleanField(widget=forms.CheckboxInput, required=True,
                                 label='Согласие на обработку персональных данных')

    class Meta:
        model = AdvUser
        fields = ('username', 'fullname', 'email', 'password', 'password2', 'consent')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']

    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['name', 'summary', 'category', 'image']


class ApplicationDesignForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['design']


class ApplicationCommentForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['comment']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

oop_django2/week_2/catalog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import UserRegistrationForm, ApplicationForm, ApplicationCommentForm, ApplicationDesignForm, CategoryForm
from django.views import generic
from .models import Application, AdvUser, Category
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import ApplicationFilter
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin


# Create your views here.
def home(request):
    num_applications_in_progress = Application.objects.all().filter(status='Принято в работу').count()
    applications_done = Application.objects.filter(status='Выполнено')

    return render(request, 'home.html', context={'num_applications_in_progress': num_applications_in_progress,
                                                  'applications_done': applications_done})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'catalog/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'catalog/register.html', {'user_form': user_form})


@login_required()
def profile(request):
    return render(request, 'catalog/profile.html')


class ApplicationList(LoginRequiredMixin, generic.ListView):
    model = Application
    template_name = 'catalog/application_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(self.request.GET, queryset=self.get_queryset())
        return context

    def get_queryset(self):
        return Application.objects.filter(client=self.request.user.id)


class ApplicationListAdmin(LoginRequiredMixin, generic.ListView):
    model = Application
    template_name = 'catalog/application_list_admin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ApplicationFilter(self.request.GET, queryset=self.get_queryset())
        return context


class ApplicationCreate(CreateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'application_form.html'
    success_url = reverse_lazy('application')

    def form_valid(self, form):
        fields = form.save(commit=False)
        fields.client = self.request.user
        fields.save()
        return super().form_valid(form)


class ApplicationDelete(DeleteView):
    model = Application
    success_url = reverse_lazy('application')


def confirm_update(request, pk, st):
    newApplication = Application.objects.get(id=pk)
    newApplication.save()

    if st == 'Выполнено':
        if request.method == 'POST':
            form = ApplicationDesignForm(request.POST, request.FILES)
            if form.is_valid():
                newApplication.design = form.cleaned_data['design']
                newApplication.status = st
                newApplication.save()
                return redirect('application-admin')
        else:
            form = ApplicationDesignForm()
        return render(request, 'catalog/update_application.html', {'form': form})

    if st == 'Принято в работу':
        if request.method == 'POST':
            form = ApplicationCommentForm(request.POST, request.FILES)
            if form.is_valid():
                newApplication.comment = form.cleaned_data['comment']
                newApplication.status = st
                newApplication.save()
                return redirect('application-admin')
        else:
            form = ApplicationCommentForm()
        return render(request, 'catalog/update_application.html', {'form': form})


class ViewCategory(LoginRequiredMixin, generic.ListView):
    model = Category
    template_name = 'catalog/categories_list.html'
    context_object_name = 'categories_list'


class CreateCategory(CreateView):
    template_name = 'catalog/category_create.html'
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('view-categories')


class DeleteCategory(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('view-categories')

oop_django2/week_2/catalog/templates/catalog/application_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="col mb-3">
        <h1>Удаление заявки</h1>

        <p>Вы уверены, что хотите удалить заявку: {{application}}?</p>

        <form action="" method="POST">
            {% csrf_token %}
            <input class="btn btn-info mb-3" type="submit" value="Удалить"/>
        </form>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/application_list.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
    <div class="col mb-3">
        <h1>Мои заявки</h1>
        <form action="" method="GET">
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Показать</button>
        </form>
        {% if application_list %}
        <ul>
            {% for application in filter.qs %}
            <li>Пользователь: {{application.client}}</li>
            <li>Название заявки: {{application.name}}</li>
            <li>Описание заявки: {{application.summary}}</li>
            <li>Категория заявки: {{application.category}}</li>
            <li>Временная метка: {{application.timestamp}}</li>
            <li>Статус заявки: {{application.status}}</li>
            {% if application.status == "Принято в работу" %}
            <li>Комментарий: {{application.comment}}</li>
            {% elif application.status == "Выполнено" %}
            <img width="150px" height="100px" src="{{ application.design.url }}">
            {% endif %}
            <li><a href="{% url 'application-delete' application.pk %}">Удалить заявку</a></li>
            <br>
            <br>
            <br>
            {% endfor %}
        </ul>
        {% else %}
        <p>Нет заявок.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/application_list_admin.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<div class="container">
    <div class="col mb-3">
        {% if perms.catalog.change_application %}
        <h1>Заявки всех пользователей</h1>
        <form action="" method="GET">
            {{ filter.form|bootstrap }}
            <button type="submit" class="btn btn-primary">Показать</button>
        </form>
        {% if application_list %}
        <ul>
            {% for application in filter.qs %}
            <li>Пользователь: {{application.client}}</li>
            <li>Название заявки: {{application.name}}</li>
            <li>Описание заявки: {{application.summary}}</li>
            <li>Категория заявки: {{application.category}}</li>
            <li>Временная метка: {{application.timestamp}}</li>
            <li>Статус заявки: {{application.status}}</li>
            <div>
                <p>Изменить статус:</p>
                <a href="{% url 'confirm-update' application.pk 'Принято в работу' %}">Статус - принято в работу</a>
                <a href="{% url 'confirm-update' application.pk  'Выполнено' %}">Статус - выполнено</a>
            </div>
            <li><a href="{% url 'application-delete' application.pk %}">Удалить заявку</a></li>
            <br>
            <br>
            <br>
            {% endfor %}
        </ul>
        {% else %}
        <p>Нет заявок.</p>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/categories_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col mb-3">
        <div>
            <h1>Управление категориями</h1>
            <a href="{% url 'create-category' %}">Добавить новую категорию</a>
        </div>

        {% if categories_list %}
        <h2>Удалить категории</h2>
        {% for category in categories_list %}
        <p>
            {{ category.name }} -
            <a href="{% url 'delete-category' category.pk %}">удалить</a>
        </p>
        {% endfor %}
        {% else %}
        <p>Не существует категорий заявок</p>
        {% endif %}
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/category_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col mb-3">
        <div>
            <h1>Удаление категории</h1>
            <p>Вы точно хотите удалить категорию?</p>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-info mb-3" type="submit">Да</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/category_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col mb-3">
        <div>
            <h1>Добавление категории</h1>
            <form method="post">
                {{form.as_p}}
                {% csrf_token %}
                <button class="btn btn-info mb-3" type="submit">Добавить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/profile.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="col mb-3">
        <ul>
            <li><a href="{% url 'application' %}">Мои заявки</a></li>
            {% if perms.catalog.change_application %}
            <li><a href="{% url 'view-categories' %}">Управление категориями</a>
            <li><a href="{% url 'application-admin' %}">Заявки всех пользователей</a></li>
            {% endif %}
            <li><a href="{% url 'application-create' %}">Создать заявку</a></li>
        </ul>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/register.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="col mb-3">
        <h1>Создание аккаунта</h1>
        <p>Зарегистрируйтесь, следуя этой форме:</p>
        <form class="col-form-label" action="." method="post">
            {{ user_form.as_p }}
            {% csrf_token %}
            <p><input class="btn btn-info mb-3" type="submit" value="Создать аккаунт"></p>
        </form>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/register_done.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="col mb-3">
        <h1>Здравствуйте {{ new_user.first_name }}!</h1>
        <p>Ваш аккаунт успешно создан. Вы можете <a href="{% url 'login' %}">войти</a>.</p>
    </div>
</div>
{% endblock %}

oop_django2/week_2/catalog/templates/catalog/update_application.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col mb-3">
        <div>
            <h1>Изменение статуса</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-info mb-3" type="submit">Добавить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}